services:
  react-vite:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.production
    image: react-vite:latest
    container_name: react-vite
    ports:
      - "${APP_PORT:-3001}:4173"
    restart: unless-stopped
    networks:
      - react-net

networks:
  react-net:
    driver: bridge
