/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppJobsRouteImport } from './routes/_app/jobs'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'

const UiLazyRouteImport = createFileRoute('/ui')()
const AppIndexLazyRouteImport = createFileRoute('/_app/')()
const AppActivityLazyRouteImport = createFileRoute('/_app/activity')()
const AppFilesLazyRouteImport = createFileRoute('/_app/files')()
const AppProfileLazyRouteImport = createFileRoute('/_app/profile')()
const AppSecurityLazyRouteImport = createFileRoute('/_app/security')()
const AuthForgotPasswordLazyRouteImport = createFileRoute(
  '/_auth/forgot-password',
)()
const AuthSignInLazyRouteImport = createFileRoute('/_auth/sign-in')()
const AuthSignUpLazyRouteImport = createFileRoute('/_auth/sign-up')()
const UiIndexLazyRouteImport = createFileRoute('/ui/')()
const UiSectionLazyRouteImport = createFileRoute('/ui/$section')()
const AppAdminApiKeysLazyRouteImport = createFileRoute('/_app/admin/api-keys')()
const AppAdminAuditLazyRouteImport = createFileRoute('/_app/admin/audit')()
const AppAdminRolesLazyRouteImport = createFileRoute('/_app/admin/roles')()
const AppAdminUsersLazyRouteImport = createFileRoute('/_app/admin/users')()
const AppAgentsIndexLazyRouteImport = createFileRoute('/_app/agents/')()
const AppAgentsAgentIdLazyRouteImport = createFileRoute(
  '/_app/agents/$agentId',
)()
const AppNodesIndexLazyRouteImport = createFileRoute('/_app/nodes/')()
const AppNodesNodeIdLazyRouteImport = createFileRoute('/_app/nodes/$nodeId')()

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const UiLazyRoute = UiLazyRouteImport.update({
  id: '/ui',
  path: '/ui',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/ui.lazy').then((d) => d.Route))
const AppIndexLazyRoute = AppIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/index.lazy').then((d) => d.Route))
const AppActivityLazyRoute = AppActivityLazyRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/activity.lazy').then((d) => d.Route))
const AppFilesLazyRoute = AppFilesLazyRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/files.lazy').then((d) => d.Route))
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/jobs.lazy').then((d) => d.Route))
const AppProfileLazyRoute = AppProfileLazyRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/profile.lazy').then((d) => d.Route))
const AppSecurityLazyRoute = AppSecurityLazyRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/security.lazy').then((d) => d.Route))
const AuthForgotPasswordLazyRoute = AuthForgotPasswordLazyRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/forgot-password.lazy').then((d) => d.Route),
)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/reset-password.lazy').then((d) => d.Route),
)
const AuthSignInLazyRoute = AuthSignInLazyRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/sign-in.lazy').then((d) => d.Route))
const AuthSignUpLazyRoute = AuthSignUpLazyRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/sign-up.lazy').then((d) => d.Route))
const UiIndexLazyRoute = UiIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UiLazyRoute,
} as any).lazy(() => import('./routes/ui.index.lazy').then((d) => d.Route))
const UiSectionLazyRoute = UiSectionLazyRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => UiLazyRoute,
} as any).lazy(() => import('./routes/ui.$section.lazy').then((d) => d.Route))
const AppAdminApiKeysLazyRoute = AppAdminApiKeysLazyRouteImport.update({
  id: '/admin/api-keys',
  path: '/admin/api-keys',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/api-keys.lazy').then((d) => d.Route),
)
const AppAdminAuditLazyRoute = AppAdminAuditLazyRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/audit.lazy').then((d) => d.Route),
)
const AppAdminRolesLazyRoute = AppAdminRolesLazyRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/roles.lazy').then((d) => d.Route),
)
const AppAdminUsersLazyRoute = AppAdminUsersLazyRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/users.lazy').then((d) => d.Route),
)
const AppAgentsIndexLazyRoute = AppAgentsIndexLazyRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/agents.index.lazy').then((d) => d.Route),
)
const AppAgentsAgentIdLazyRoute = AppAgentsAgentIdLazyRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/agents.$agentId.lazy').then((d) => d.Route),
)
const AppNodesIndexLazyRoute = AppNodesIndexLazyRouteImport.update({
  id: '/nodes/',
  path: '/nodes/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/nodes.index.lazy').then((d) => d.Route),
)
const AppNodesNodeIdLazyRoute = AppNodesNodeIdLazyRouteImport.update({
  id: '/nodes/$nodeId',
  path: '/nodes/$nodeId',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/nodes.$nodeId.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexLazyRoute
  '/ui': typeof UiLazyRouteWithChildren
  '/jobs': typeof AppJobsRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/activity': typeof AppActivityLazyRoute
  '/files': typeof AppFilesLazyRoute
  '/profile': typeof AppProfileLazyRoute
  '/security': typeof AppSecurityLazyRoute
  '/forgot-password': typeof AuthForgotPasswordLazyRoute
  '/sign-in': typeof AuthSignInLazyRoute
  '/sign-up': typeof AuthSignUpLazyRoute
  '/ui/$section': typeof UiSectionLazyRoute
  '/ui/': typeof UiIndexLazyRoute
  '/admin/api-keys': typeof AppAdminApiKeysLazyRoute
  '/admin/audit': typeof AppAdminAuditLazyRoute
  '/admin/roles': typeof AppAdminRolesLazyRoute
  '/admin/users': typeof AppAdminUsersLazyRoute
  '/agents/$agentId': typeof AppAgentsAgentIdLazyRoute
  '/nodes/$nodeId': typeof AppNodesNodeIdLazyRoute
  '/agents/': typeof AppAgentsIndexLazyRoute
  '/nodes/': typeof AppNodesIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexLazyRoute
  '/jobs': typeof AppJobsRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/activity': typeof AppActivityLazyRoute
  '/files': typeof AppFilesLazyRoute
  '/profile': typeof AppProfileLazyRoute
  '/security': typeof AppSecurityLazyRoute
  '/forgot-password': typeof AuthForgotPasswordLazyRoute
  '/sign-in': typeof AuthSignInLazyRoute
  '/sign-up': typeof AuthSignUpLazyRoute
  '/ui/$section': typeof UiSectionLazyRoute
  '/ui': typeof UiIndexLazyRoute
  '/admin/api-keys': typeof AppAdminApiKeysLazyRoute
  '/admin/audit': typeof AppAdminAuditLazyRoute
  '/admin/roles': typeof AppAdminRolesLazyRoute
  '/admin/users': typeof AppAdminUsersLazyRoute
  '/agents/$agentId': typeof AppAgentsAgentIdLazyRoute
  '/nodes/$nodeId': typeof AppNodesNodeIdLazyRoute
  '/agents': typeof AppAgentsIndexLazyRoute
  '/nodes': typeof AppNodesIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/ui': typeof UiLazyRouteWithChildren
  '/_app/jobs': typeof AppJobsRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_app/activity': typeof AppActivityLazyRoute
  '/_app/files': typeof AppFilesLazyRoute
  '/_app/profile': typeof AppProfileLazyRoute
  '/_app/security': typeof AppSecurityLazyRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordLazyRoute
  '/_auth/sign-in': typeof AuthSignInLazyRoute
  '/_auth/sign-up': typeof AuthSignUpLazyRoute
  '/ui/$section': typeof UiSectionLazyRoute
  '/_app/': typeof AppIndexLazyRoute
  '/ui/': typeof UiIndexLazyRoute
  '/_app/admin/api-keys': typeof AppAdminApiKeysLazyRoute
  '/_app/admin/audit': typeof AppAdminAuditLazyRoute
  '/_app/admin/roles': typeof AppAdminRolesLazyRoute
  '/_app/admin/users': typeof AppAdminUsersLazyRoute
  '/_app/agents/$agentId': typeof AppAgentsAgentIdLazyRoute
  '/_app/nodes/$nodeId': typeof AppNodesNodeIdLazyRoute
  '/_app/agents/': typeof AppAgentsIndexLazyRoute
  '/_app/nodes/': typeof AppNodesIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ui'
    | '/jobs'
    | '/reset-password'
    | '/activity'
    | '/files'
    | '/profile'
    | '/security'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/ui/$section'
    | '/ui/'
    | '/admin/api-keys'
    | '/admin/audit'
    | '/admin/roles'
    | '/admin/users'
    | '/agents/$agentId'
    | '/nodes/$nodeId'
    | '/agents/'
    | '/nodes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/jobs'
    | '/reset-password'
    | '/activity'
    | '/files'
    | '/profile'
    | '/security'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/ui/$section'
    | '/ui'
    | '/admin/api-keys'
    | '/admin/audit'
    | '/admin/roles'
    | '/admin/users'
    | '/agents/$agentId'
    | '/nodes/$nodeId'
    | '/agents'
    | '/nodes'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/ui'
    | '/_app/jobs'
    | '/_auth/reset-password'
    | '/_app/activity'
    | '/_app/files'
    | '/_app/profile'
    | '/_app/security'
    | '/_auth/forgot-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/ui/$section'
    | '/_app/'
    | '/ui/'
    | '/_app/admin/api-keys'
    | '/_app/admin/audit'
    | '/_app/admin/roles'
    | '/_app/admin/users'
    | '/_app/agents/$agentId'
    | '/_app/nodes/$nodeId'
    | '/_app/agents/'
    | '/_app/nodes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  UiLazyRoute: typeof UiLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui': {
      id: '/ui'
      path: '/ui'
      fullPath: '/ui'
      preLoaderRoute: typeof UiLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/files': {
      id: '/_app/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AppFilesLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security': {
      id: '/_app/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AppSecurityLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/ui/': {
      id: '/ui/'
      path: '/'
      fullPath: '/ui/'
      preLoaderRoute: typeof UiIndexLazyRouteImport
      parentRoute: typeof UiLazyRoute
    }
    '/ui/$section': {
      id: '/ui/$section'
      path: '/$section'
      fullPath: '/ui/$section'
      preLoaderRoute: typeof UiSectionLazyRouteImport
      parentRoute: typeof UiLazyRoute
    }
    '/_app/admin/api-keys': {
      id: '/_app/admin/api-keys'
      path: '/admin/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AppAdminApiKeysLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/roles': {
      id: '/_app/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AppAdminRolesLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/': {
      id: '/_app/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AppAgentsIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/$agentId': {
      id: '/_app/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AppAgentsAgentIdLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nodes/': {
      id: '/_app/nodes/'
      path: '/nodes'
      fullPath: '/nodes/'
      preLoaderRoute: typeof AppNodesIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nodes/$nodeId': {
      id: '/_app/nodes/$nodeId'
      path: '/nodes/$nodeId'
      fullPath: '/nodes/$nodeId'
      preLoaderRoute: typeof AppNodesNodeIdLazyRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppJobsRoute: typeof AppJobsRoute
  AppActivityLazyRoute: typeof AppActivityLazyRoute
  AppFilesLazyRoute: typeof AppFilesLazyRoute
  AppProfileLazyRoute: typeof AppProfileLazyRoute
  AppSecurityLazyRoute: typeof AppSecurityLazyRoute
  AppIndexLazyRoute: typeof AppIndexLazyRoute
  AppAdminApiKeysLazyRoute: typeof AppAdminApiKeysLazyRoute
  AppAdminAuditLazyRoute: typeof AppAdminAuditLazyRoute
  AppAdminRolesLazyRoute: typeof AppAdminRolesLazyRoute
  AppAdminUsersLazyRoute: typeof AppAdminUsersLazyRoute
  AppAgentsAgentIdLazyRoute: typeof AppAgentsAgentIdLazyRoute
  AppNodesNodeIdLazyRoute: typeof AppNodesNodeIdLazyRoute
  AppAgentsIndexLazyRoute: typeof AppAgentsIndexLazyRoute
  AppNodesIndexLazyRoute: typeof AppNodesIndexLazyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppJobsRoute: AppJobsRoute,
  AppActivityLazyRoute: AppActivityLazyRoute,
  AppFilesLazyRoute: AppFilesLazyRoute,
  AppProfileLazyRoute: AppProfileLazyRoute,
  AppSecurityLazyRoute: AppSecurityLazyRoute,
  AppIndexLazyRoute: AppIndexLazyRoute,
  AppAdminApiKeysLazyRoute: AppAdminApiKeysLazyRoute,
  AppAdminAuditLazyRoute: AppAdminAuditLazyRoute,
  AppAdminRolesLazyRoute: AppAdminRolesLazyRoute,
  AppAdminUsersLazyRoute: AppAdminUsersLazyRoute,
  AppAgentsAgentIdLazyRoute: AppAgentsAgentIdLazyRoute,
  AppNodesNodeIdLazyRoute: AppNodesNodeIdLazyRoute,
  AppAgentsIndexLazyRoute: AppAgentsIndexLazyRoute,
  AppNodesIndexLazyRoute: AppNodesIndexLazyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthForgotPasswordLazyRoute: typeof AuthForgotPasswordLazyRoute
  AuthSignInLazyRoute: typeof AuthSignInLazyRoute
  AuthSignUpLazyRoute: typeof AuthSignUpLazyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthForgotPasswordLazyRoute: AuthForgotPasswordLazyRoute,
  AuthSignInLazyRoute: AuthSignInLazyRoute,
  AuthSignUpLazyRoute: AuthSignUpLazyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface UiLazyRouteChildren {
  UiSectionLazyRoute: typeof UiSectionLazyRoute
  UiIndexLazyRoute: typeof UiIndexLazyRoute
}

const UiLazyRouteChildren: UiLazyRouteChildren = {
  UiSectionLazyRoute: UiSectionLazyRoute,
  UiIndexLazyRoute: UiIndexLazyRoute,
}

const UiLazyRouteWithChildren =
  UiLazyRoute._addFileChildren(UiLazyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  UiLazyRoute: UiLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
