/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppUsersUserIdRouteImport } from './routes/_app/users/$userId'

const AppIndexLazyRouteImport = createFileRoute('/_app/')()
const AuthSignUpLazyRouteImport = createFileRoute('/_auth/sign-up')()
const AuthSignInLazyRouteImport = createFileRoute('/_auth/sign-in')()
const AuthForgotPasswordLazyRouteImport = createFileRoute(
  '/_auth/forgot-password',
)()
const AppUiLazyRouteImport = createFileRoute('/_app/ui')()
const AppProfileLazyRouteImport = createFileRoute('/_app/profile')()
const AppUsersIndexLazyRouteImport = createFileRoute('/_app/users/')()

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexLazyRoute = AppIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/index.lazy').then((d) => d.Route))
const AuthSignUpLazyRoute = AuthSignUpLazyRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/sign-up.lazy').then((d) => d.Route))
const AuthSignInLazyRoute = AuthSignInLazyRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/sign-in.lazy').then((d) => d.Route))
const AuthForgotPasswordLazyRoute = AuthForgotPasswordLazyRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/forgot-password.lazy').then((d) => d.Route),
)
const AppUiLazyRoute = AppUiLazyRouteImport.update({
  id: '/ui',
  path: '/ui',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/ui.lazy').then((d) => d.Route))
const AppProfileLazyRoute = AppProfileLazyRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/profile.lazy').then((d) => d.Route))
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/reset-password.lazy').then((d) => d.Route),
)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIndexLazyRoute = AppUsersIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUsersRoute,
} as any).lazy(() =>
  import('./routes/_app/users/index.lazy').then((d) => d.Route),
)
const AppUsersUserIdRoute = AppUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AppUsersRoute,
} as any).lazy(() =>
  import('./routes/_app/users/$userId.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/users': typeof AppUsersRouteWithChildren
  '/reset-password': typeof AuthResetPasswordRoute
  '/profile': typeof AppProfileLazyRoute
  '/ui': typeof AppUiLazyRoute
  '/forgot-password': typeof AuthForgotPasswordLazyRoute
  '/sign-in': typeof AuthSignInLazyRoute
  '/sign-up': typeof AuthSignUpLazyRoute
  '/': typeof AppIndexLazyRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/users/': typeof AppUsersIndexLazyRoute
}
export interface FileRoutesByTo {
  '/reset-password': typeof AuthResetPasswordRoute
  '/profile': typeof AppProfileLazyRoute
  '/ui': typeof AppUiLazyRoute
  '/forgot-password': typeof AuthForgotPasswordLazyRoute
  '/sign-in': typeof AuthSignInLazyRoute
  '/sign-up': typeof AuthSignUpLazyRoute
  '/': typeof AppIndexLazyRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/users': typeof AppUsersIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/users': typeof AppUsersRouteWithChildren
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_app/profile': typeof AppProfileLazyRoute
  '/_app/ui': typeof AppUiLazyRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordLazyRoute
  '/_auth/sign-in': typeof AuthSignInLazyRoute
  '/_auth/sign-up': typeof AuthSignUpLazyRoute
  '/_app/': typeof AppIndexLazyRoute
  '/_app/users/$userId': typeof AppUsersUserIdRoute
  '/_app/users/': typeof AppUsersIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/users'
    | '/reset-password'
    | '/profile'
    | '/ui'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/'
    | '/users/$userId'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/reset-password'
    | '/profile'
    | '/ui'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/'
    | '/users/$userId'
    | '/users'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/users'
    | '/_auth/reset-password'
    | '/_app/profile'
    | '/_app/ui'
    | '/_auth/forgot-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_app/'
    | '/_app/users/$userId'
    | '/_app/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/ui': {
      id: '/_app/ui'
      path: '/ui'
      fullPath: '/ui'
      preLoaderRoute: typeof AppUiLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexLazyRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/_app/users/$userId': {
      id: '/_app/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AppUsersUserIdRouteImport
      parentRoute: typeof AppUsersRoute
    }
  }
}

interface AppUsersRouteChildren {
  AppUsersUserIdRoute: typeof AppUsersUserIdRoute
  AppUsersIndexLazyRoute: typeof AppUsersIndexLazyRoute
}

const AppUsersRouteChildren: AppUsersRouteChildren = {
  AppUsersUserIdRoute: AppUsersUserIdRoute,
  AppUsersIndexLazyRoute: AppUsersIndexLazyRoute,
}

const AppUsersRouteWithChildren = AppUsersRoute._addFileChildren(
  AppUsersRouteChildren,
)

interface AppRouteChildren {
  AppUsersRoute: typeof AppUsersRouteWithChildren
  AppProfileLazyRoute: typeof AppProfileLazyRoute
  AppUiLazyRoute: typeof AppUiLazyRoute
  AppIndexLazyRoute: typeof AppIndexLazyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppUsersRoute: AppUsersRouteWithChildren,
  AppProfileLazyRoute: AppProfileLazyRoute,
  AppUiLazyRoute: AppUiLazyRoute,
  AppIndexLazyRoute: AppIndexLazyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthForgotPasswordLazyRoute: typeof AuthForgotPasswordLazyRoute
  AuthSignInLazyRoute: typeof AuthSignInLazyRoute
  AuthSignUpLazyRoute: typeof AuthSignUpLazyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthForgotPasswordLazyRoute: AuthForgotPasswordLazyRoute,
  AuthSignInLazyRoute: AuthSignInLazyRoute,
  AuthSignUpLazyRoute: AuthSignUpLazyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
