/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as AuthImport } from './routes/auth'
import { Route as PrivateImport } from './routes/_private'

// Create Virtual Routes

const PrivateIndexLazyImport = createFileRoute('/_private/')()
const AuthSignUpLazyImport = createFileRoute('/auth/signUp')()
const AuthSignInLazyImport = createFileRoute('/auth/signIn')()
const AuthRecoveryPasswordLazyImport = createFileRoute(
  '/auth/recovery-password',
)()

// Create/Update Routes

const ResetPasswordRoute = ResetPasswordImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const PrivateRoute = PrivateImport.update({
  id: '/_private',
  getParentRoute: () => rootRoute,
} as any)

const PrivateIndexLazyRoute = PrivateIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRoute,
} as any).lazy(() =>
  import('./routes/_private/index.lazy').then((d) => d.Route),
)

const AuthSignUpLazyRoute = AuthSignUpLazyImport.update({
  id: '/signUp',
  path: '/signUp',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/auth/signUp.lazy').then((d) => d.Route))

const AuthSignInLazyRoute = AuthSignInLazyImport.update({
  id: '/signIn',
  path: '/signIn',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/auth/signIn.lazy').then((d) => d.Route))

const AuthRecoveryPasswordLazyRoute = AuthRecoveryPasswordLazyImport.update({
  id: '/recovery-password',
  path: '/recovery-password',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/auth/recovery-password.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/auth/recovery-password': {
      id: '/auth/recovery-password'
      path: '/recovery-password'
      fullPath: '/auth/recovery-password'
      preLoaderRoute: typeof AuthRecoveryPasswordLazyImport
      parentRoute: typeof AuthImport
    }
    '/auth/signIn': {
      id: '/auth/signIn'
      path: '/signIn'
      fullPath: '/auth/signIn'
      preLoaderRoute: typeof AuthSignInLazyImport
      parentRoute: typeof AuthImport
    }
    '/auth/signUp': {
      id: '/auth/signUp'
      path: '/signUp'
      fullPath: '/auth/signUp'
      preLoaderRoute: typeof AuthSignUpLazyImport
      parentRoute: typeof AuthImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexLazyImport
      parentRoute: typeof PrivateImport
    }
  }
}

// Create and export the route tree

interface PrivateRouteChildren {
  PrivateIndexLazyRoute: typeof PrivateIndexLazyRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateIndexLazyRoute: PrivateIndexLazyRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

interface AuthRouteChildren {
  AuthRecoveryPasswordLazyRoute: typeof AuthRecoveryPasswordLazyRoute
  AuthSignInLazyRoute: typeof AuthSignInLazyRoute
  AuthSignUpLazyRoute: typeof AuthSignUpLazyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthRecoveryPasswordLazyRoute: AuthRecoveryPasswordLazyRoute,
  AuthSignInLazyRoute: AuthSignInLazyRoute,
  AuthSignUpLazyRoute: AuthSignUpLazyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof PrivateRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/auth/recovery-password': typeof AuthRecoveryPasswordLazyRoute
  '/auth/signIn': typeof AuthSignInLazyRoute
  '/auth/signUp': typeof AuthSignUpLazyRoute
  '/': typeof PrivateIndexLazyRoute
}

export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/auth/recovery-password': typeof AuthRecoveryPasswordLazyRoute
  '/auth/signIn': typeof AuthSignInLazyRoute
  '/auth/signUp': typeof AuthSignUpLazyRoute
  '/': typeof PrivateIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_private': typeof PrivateRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/auth/recovery-password': typeof AuthRecoveryPasswordLazyRoute
  '/auth/signIn': typeof AuthSignInLazyRoute
  '/auth/signUp': typeof AuthSignUpLazyRoute
  '/_private/': typeof PrivateIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/auth'
    | '/reset-password'
    | '/auth/recovery-password'
    | '/auth/signIn'
    | '/auth/signUp'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/auth/recovery-password'
    | '/auth/signIn'
    | '/auth/signUp'
    | '/'
  id:
    | '__root__'
    | '/_private'
    | '/auth'
    | '/reset-password'
    | '/auth/recovery-password'
    | '/auth/signIn'
    | '/auth/signUp'
    | '/_private/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  PrivateRoute: typeof PrivateRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

const rootRouteChildren: RootRouteChildren = {
  PrivateRoute: PrivateRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_private",
        "/auth",
        "/reset-password"
      ]
    },
    "/_private": {
      "filePath": "_private.tsx",
      "children": [
        "/_private/"
      ]
    },
    "/auth": {
      "filePath": "auth.tsx",
      "children": [
        "/auth/recovery-password",
        "/auth/signIn",
        "/auth/signUp"
      ]
    },
    "/reset-password": {
      "filePath": "reset-password.tsx"
    },
    "/auth/recovery-password": {
      "filePath": "auth/recovery-password.lazy.tsx",
      "parent": "/auth"
    },
    "/auth/signIn": {
      "filePath": "auth/signIn.lazy.tsx",
      "parent": "/auth"
    },
    "/auth/signUp": {
      "filePath": "auth/signUp.lazy.tsx",
      "parent": "/auth"
    },
    "/_private/": {
      "filePath": "_private/index.lazy.tsx",
      "parent": "/_private"
    }
  }
}
ROUTE_MANIFEST_END */
